/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.Savindu.Controller.Controller;
import com.Savindu.Controller.ServerController;
import com.Savindu.Entity.User;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
//import javax.persistence.Query;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import model.empmodel;
import net.proteanit.sql.DbUtils;
import service.empservice;

/**
 *
 * @author Nuwanga
 */
public class AppInterface extends javax.swing.JFrame {

    /**
     * Creates new form AppInterface
     */
    private static String branchname;
    public AppInterface() {
        initComponents();
    }
    
    public AppInterface(String branchname) {
        initComponents();
        this.branchname = branchname;
    }
    
    void viewPanel(String cname) {
        CardLayout cL = (CardLayout) jPanel3.getLayout();
        cL.show(jPanel3, cname);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        btnviewreports = new javax.swing.JButton();
        btnaddreports = new javax.swing.JButton();
        btnchangesettings = new javax.swing.JButton();
        btnmainmenu = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        mainmenucard = new javax.swing.JPanel();
        mainmenuvr = new javax.swing.JButton();
        mainmenuar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        addreportscard = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        btnaddusertable = new javax.swing.JButton();
        btnaddattendancetable = new javax.swing.JButton();
        btnaddnotes = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        btnaddleavetable1 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        viewreportscard = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        viewreportmonth = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        viewreportyear = new javax.swing.JComboBox<>();
        btnsearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablevr = new javax.swing.JTable();
        btngeneratepdf = new javax.swing.JButton();
        changesettingscard = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        settingsun = new javax.swing.JTextField();
        settingscpw = new javax.swing.JPasswordField();
        btnconfirm = new javax.swing.JButton();
        settingsnpw = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        settingspw = new javax.swing.JPasswordField();
        settingsnun = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        addusertable = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableuser = new javax.swing.JTable();
        addleavetable = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableleave = new javax.swing.JTable();
        addattendancetable = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableatt = new javax.swing.JTable();
        addnotes = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        addnote = new javax.swing.JTextArea();
        btnaddnote = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1885, 990));
        setPreferredSize(new java.awt.Dimension(1885, 990));

        jPanel1.setBackground(new java.awt.Color(0, 102, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(265, 990));

        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 4));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/agrilogotrans.png"))); // NOI18N

        btnviewreports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/viewr.png"))); // NOI18N
        btnviewreports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewreportsActionPerformed(evt);
            }
        });

        btnaddreports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Addr.png"))); // NOI18N
        btnaddreports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddreportsActionPerformed(evt);
            }
        });

        btnchangesettings.setBackground(new java.awt.Color(204, 204, 204));
        btnchangesettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/setting.png"))); // NOI18N
        btnchangesettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchangesettingsActionPerformed(evt);
            }
        });

        btnmainmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu.png"))); // NOI18N
        btnmainmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmainmenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnchangesettings, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnviewreports, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnaddreports, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnmainmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135)
                .addComponent(btnmainmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(btnaddreports, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(btnviewreports, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(btnchangesettings, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 102, 51));

        jLabel2.setBackground(new java.awt.Color(0, 51, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 71)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Department of Agrarian Development - Galle");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 102, 51));
        jPanel3.setLayout(new java.awt.CardLayout());

        mainmenucard.setBackground(new java.awt.Color(204, 255, 204));

        mainmenuvr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/viewreportbutton.png"))); // NOI18N
        mainmenuvr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainmenuvrActionPerformed(evt);
            }
        });

        mainmenuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttonadddata.png"))); // NOI18N
        mainmenuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainmenuarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("View Reports");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Add Reports");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setText("Main Menu");

        javax.swing.GroupLayout mainmenucardLayout = new javax.swing.GroupLayout(mainmenucard);
        mainmenucard.setLayout(mainmenucardLayout);
        mainmenucardLayout.setHorizontalGroup(
            mainmenucardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainmenucardLayout.createSequentialGroup()
                .addGroup(mainmenucardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainmenucardLayout.createSequentialGroup()
                        .addGap(322, 322, 322)
                        .addComponent(mainmenuvr))
                    .addGroup(mainmenucardLayout.createSequentialGroup()
                        .addGap(392, 392, 392)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(mainmenucardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainmenucardLayout.createSequentialGroup()
                        .addGap(279, 279, 279)
                        .addComponent(mainmenuar))
                    .addGroup(mainmenucardLayout.createSequentialGroup()
                        .addGap(350, 350, 350)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(371, 371, 371))
            .addGroup(mainmenucardLayout.createSequentialGroup()
                .addGap(691, 691, 691)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainmenucardLayout.setVerticalGroup(
            mainmenucardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainmenucardLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124)
                .addGroup(mainmenucardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mainmenuar, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                    .addComponent(mainmenuvr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(mainmenucardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(237, Short.MAX_VALUE))
        );

        jPanel3.add(mainmenucard, "mainmenucard");

        addreportscard.setBackground(new java.awt.Color(204, 255, 204));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setText("Add Reports");

        btnaddusertable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttonadddata.png"))); // NOI18N
        btnaddusertable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddusertableActionPerformed(evt);
            }
        });

        btnaddattendancetable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttonadddata.png"))); // NOI18N
        btnaddattendancetable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddattendancetableActionPerformed(evt);
            }
        });

        btnaddnotes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttonadddata.png"))); // NOI18N
        btnaddnotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddnotesActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel17.setText("Add User Table");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel18.setText("Add Attendance Table");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel19.setText("Add Leave Table");

        btnaddleavetable1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttonadddata.png"))); // NOI18N
        btnaddleavetable1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddleavetable1ActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel20.setText("Add Field Officer Programmes");

        javax.swing.GroupLayout addreportscardLayout = new javax.swing.GroupLayout(addreportscard);
        addreportscard.setLayout(addreportscardLayout);
        addreportscardLayout.setHorizontalGroup(
            addreportscardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addreportscardLayout.createSequentialGroup()
                .addGroup(addreportscardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addreportscardLayout.createSequentialGroup()
                        .addGap(704, 704, 704)
                        .addComponent(jLabel13))
                    .addGroup(addreportscardLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addGroup(addreportscardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(addreportscardLayout.createSequentialGroup()
                                .addComponent(btnaddusertable, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(btnaddattendancetable, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(addreportscardLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel18)
                                .addGap(11, 11, 11)))
                        .addGroup(addreportscardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addreportscardLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(btnaddleavetable1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(btnaddnotes, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(addreportscardLayout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(jLabel19)
                                .addGap(67, 67, 67)
                                .addComponent(jLabel20)))))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        addreportscardLayout.setVerticalGroup(
            addreportscardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addreportscardLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(142, 142, 142)
                .addGroup(addreportscardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnaddattendancetable, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnaddleavetable1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnaddusertable, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnaddnotes, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(addreportscardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(232, Short.MAX_VALUE))
        );

        jPanel3.add(addreportscard, "addreportscard");

        viewreportscard.setBackground(new java.awt.Color(204, 255, 204));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setText("View Reports");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel14.setText("Month");

        viewreportmonth.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        viewreportmonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" }));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel15.setText("Year");

        viewreportyear.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        viewreportyear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040", "2041", "2042", "2043", "2044", "2045" }));
        viewreportyear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewreportyearActionPerformed(evt);
            }
        });

        btnsearch.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnsearch.setText("Search");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });

        tablevr.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablevr);

        btngeneratepdf.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btngeneratepdf.setText("Generate PDF Report");
        btngeneratepdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngeneratepdfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout viewreportscardLayout = new javax.swing.GroupLayout(viewreportscard);
        viewreportscard.setLayout(viewreportscardLayout);
        viewreportscardLayout.setHorizontalGroup(
            viewreportscardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewreportscardLayout.createSequentialGroup()
                .addGroup(viewreportscardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewreportscardLayout.createSequentialGroup()
                        .addGap(670, 670, 670)
                        .addComponent(jLabel12))
                    .addGroup(viewreportscardLayout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addGroup(viewreportscardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 954, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(viewreportscardLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(viewreportmonth, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(195, 195, 195)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(viewreportyear, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(227, 227, 227)
                                .addComponent(btnsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(viewreportscardLayout.createSequentialGroup()
                        .addGap(643, 643, 643)
                        .addComponent(btngeneratepdf, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(345, Short.MAX_VALUE))
        );
        viewreportscardLayout.setVerticalGroup(
            viewreportscardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewreportscardLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(viewreportscardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(viewreportscardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnsearch, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(viewreportmonth, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, viewreportscardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewreportyear, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(49, 49, 49)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(btngeneratepdf, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        jPanel3.add(viewreportscard, "viewreportscard");

        changesettingscard.setBackground(new java.awt.Color(204, 255, 204));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Change Password");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Change Username");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel7.setText("Username");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel8.setText("Current Password");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel9.setText("New Password");

        settingsun.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        settingscpw.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        btnconfirm.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnconfirm.setText("Confirm");
        btnconfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconfirmActionPerformed(evt);
            }
        });

        settingsnpw.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel16.setText("Current Password");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel10.setText("New Username");

        settingspw.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        settingsnun.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        settingsnun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsnunActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton1.setText("Confirm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout changesettingscardLayout = new javax.swing.GroupLayout(changesettingscard);
        changesettingscard.setLayout(changesettingscardLayout);
        changesettingscardLayout.setHorizontalGroup(
            changesettingscardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changesettingscardLayout.createSequentialGroup()
                .addGroup(changesettingscardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(changesettingscardLayout.createSequentialGroup()
                        .addGap(639, 639, 639)
                        .addComponent(jLabel5))
                    .addGroup(changesettingscardLayout.createSequentialGroup()
                        .addGap(634, 634, 634)
                        .addComponent(jLabel6))
                    .addGroup(changesettingscardLayout.createSequentialGroup()
                        .addGap(456, 456, 456)
                        .addGroup(changesettingscardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, changesettingscardLayout.createSequentialGroup()
                                .addGroup(changesettingscardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(changesettingscardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(settingsun, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                                    .addComponent(settingscpw)
                                    .addComponent(settingsnpw)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, changesettingscardLayout.createSequentialGroup()
                                .addGroup(changesettingscardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(changesettingscardLayout.createSequentialGroup()
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, Short.MAX_VALUE))
                                    .addGroup(changesettingscardLayout.createSequentialGroup()
                                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(148, 148, 148)))
                                .addGroup(changesettingscardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(settingspw, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(settingsnun, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(88, 88, 88))))
                    .addGroup(changesettingscardLayout.createSequentialGroup()
                        .addGap(649, 649, 649)
                        .addComponent(btnconfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(changesettingscardLayout.createSequentialGroup()
                        .addGap(652, 652, 652)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(442, Short.MAX_VALUE))
        );
        changesettingscardLayout.setVerticalGroup(
            changesettingscardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changesettingscardLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(changesettingscardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(settingsun, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19)
                .addGroup(changesettingscardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(settingscpw, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(changesettingscardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(settingsnpw, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addComponent(btnconfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(changesettingscardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(changesettingscardLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(settingspw, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(changesettingscardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(settingsnun, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        jPanel3.add(changesettingscard, "changesettingscard");

        addusertable.setBackground(new java.awt.Color(204, 255, 204));

        tableuser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableuser);

        javax.swing.GroupLayout addusertableLayout = new javax.swing.GroupLayout(addusertable);
        addusertable.setLayout(addusertableLayout);
        addusertableLayout.setHorizontalGroup(
            addusertableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addusertableLayout.createSequentialGroup()
                .addGap(283, 283, 283)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1064, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(261, Short.MAX_VALUE))
        );
        addusertableLayout.setVerticalGroup(
            addusertableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addusertableLayout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(284, Short.MAX_VALUE))
        );

        jPanel3.add(addusertable, "addusertable");

        addleavetable.setBackground(new java.awt.Color(204, 255, 204));

        tableleave.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tableleave);

        javax.swing.GroupLayout addleavetableLayout = new javax.swing.GroupLayout(addleavetable);
        addleavetable.setLayout(addleavetableLayout);
        addleavetableLayout.setHorizontalGroup(
            addleavetableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addleavetableLayout.createSequentialGroup()
                .addGap(282, 282, 282)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1078, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(248, Short.MAX_VALUE))
        );
        addleavetableLayout.setVerticalGroup(
            addleavetableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addleavetableLayout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(287, Short.MAX_VALUE))
        );

        jPanel3.add(addleavetable, "addleavetable");

        addattendancetable.setBackground(new java.awt.Color(204, 255, 204));

        tableatt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tableatt);

        javax.swing.GroupLayout addattendancetableLayout = new javax.swing.GroupLayout(addattendancetable);
        addattendancetable.setLayout(addattendancetableLayout);
        addattendancetableLayout.setHorizontalGroup(
            addattendancetableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addattendancetableLayout.createSequentialGroup()
                .addGap(276, 276, 276)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 1079, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(253, Short.MAX_VALUE))
        );
        addattendancetableLayout.setVerticalGroup(
            addattendancetableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addattendancetableLayout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(288, Short.MAX_VALUE))
        );

        jPanel3.add(addattendancetable, "addattendancetable");

        addnotes.setBackground(new java.awt.Color(204, 255, 204));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel21.setText("Enter Field Officer Programme");

        jScrollPane5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        addnote.setColumns(20);
        addnote.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        addnote.setRows(5);
        jScrollPane5.setViewportView(addnote);

        btnaddnote.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnaddnote.setText("Add");
        btnaddnote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddnoteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addnotesLayout = new javax.swing.GroupLayout(addnotes);
        addnotes.setLayout(addnotesLayout);
        addnotesLayout.setHorizontalGroup(
            addnotesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addnotesLayout.createSequentialGroup()
                .addGroup(addnotesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addnotesLayout.createSequentialGroup()
                        .addGap(614, 614, 614)
                        .addComponent(jLabel21))
                    .addGroup(addnotesLayout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 1124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addnotesLayout.createSequentialGroup()
                        .addGap(670, 670, 670)
                        .addComponent(btnaddnote, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(234, Short.MAX_VALUE))
        );
        addnotesLayout.setVerticalGroup(
            addnotesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addnotesLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel21)
                .addGap(37, 37, 37)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(btnaddnote, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(172, Short.MAX_VALUE))
        );

        jPanel3.add(addnotes, "addnotes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 999, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnmainmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmainmenuActionPerformed
        // TODO add your handling code here:
        viewPanel("mainmenucard");
    }//GEN-LAST:event_btnmainmenuActionPerformed

    private void btnviewreportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewreportsActionPerformed
        // TODO add your handling code here:
        ServerController sc = new ServerController();
        tablevr.setModel(DbUtils.resultSetToTableModel(sc.getAttList()));
        viewPanel("viewreportscard");
        
    }//GEN-LAST:event_btnviewreportsActionPerformed

    private void btnchangesettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchangesettingsActionPerformed
        // TODO add your handling code here:
        settingsun.setText("");
        settingscpw.setText("");
        settingsnpw.setText("");
        settingspw.setText("");
        settingsnun.setText("");
        viewPanel("changesettingscard");
    }//GEN-LAST:event_btnchangesettingsActionPerformed

    private void btnaddreportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddreportsActionPerformed
        // TODO add your handling code here:
        viewPanel("addreportscard");
    }//GEN-LAST:event_btnaddreportsActionPerformed

    private void mainmenuvrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainmenuvrActionPerformed
        // TODO add your handling code here:
        ServerController sc = new ServerController();
        tablevr.setModel(DbUtils.resultSetToTableModel(sc.getAttList()));
        viewPanel("viewreportscard");
    }//GEN-LAST:event_mainmenuvrActionPerformed

    private void mainmenuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainmenuarActionPerformed
        // TODO add your handling code here:
        viewPanel("addreportscard");
    }//GEN-LAST:event_mainmenuarActionPerformed

    private void btnconfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconfirmActionPerformed
        // TODO add your handling code here:
        empmodel em = new empmodel();
        em.setBranchname(branchname);
        em.setUsername(settingsun.getText());
        em.setPassword(settingscpw.getText());
        em.setNewpassword(settingsnpw.getText());
        
        empservice es = new empservice();
        
        Boolean status = es.changepw(em);
      
      if (status == true){
          viewPanel("mainmenucard");
      }else{
          
          JOptionPane.showMessageDialog(null, "Username or Password Incorrect");
          
      }
    }//GEN-LAST:event_btnconfirmActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        empmodel em = new empmodel();
        em.setBranchname(branchname);
        
        em.setPassword(settingspw.getText());
        em.setNewusername(settingsnun.getText());
        
        empservice es = new empservice();
        
        Boolean status = es.changeun(em);
      
      if (status == true){
          viewPanel("mainmenucard");
      }else{
          
          JOptionPane.showMessageDialog(null, "Password Incorrect");
          
      }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void settingsnunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsnunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_settingsnunActionPerformed

    private void btnaddusertableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddusertableActionPerformed
         //TODO add your handling code here:
        empservice es = new empservice();
        tableuser.setModel(DbUtils.resultSetToTableModel(es.getemployees()));
        viewPanel("addusertable");
        ServerController ss = new ServerController();
        ss.insertUserList();
    }//GEN-LAST:event_btnaddusertableActionPerformed

    private void btnaddattendancetableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddattendancetableActionPerformed
        // TODO add your handling code here:
        empservice es = new empservice();
        tableatt.setModel(DbUtils.resultSetToTableModel(es.getatt()));
        viewPanel("addattendancetable");
        ServerController ss = new ServerController();
        ss.insertAttList();
    }//GEN-LAST:event_btnaddattendancetableActionPerformed

    private void btnaddnotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddnotesActionPerformed
        // TODO add your handling code here:
        viewPanel("addnotes");
    }//GEN-LAST:event_btnaddnotesActionPerformed

    private void btnaddleavetable1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddleavetable1ActionPerformed
        // TODO add your handling code here:
        empservice es = new empservice();
        tableleave.setModel(DbUtils.resultSetToTableModel(es.getleave()));
        viewPanel("addleavetable");
        ServerController ss = new ServerController();
        ss.insertLeaveList();
    }//GEN-LAST:event_btnaddleavetable1ActionPerformed

    private void viewreportyearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewreportyearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewreportyearActionPerformed

    private void btnaddnoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddnoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnaddnoteActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsearchActionPerformed

    private void btngeneratepdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngeneratepdfActionPerformed
        // TODO add your handling code here:
        ServerController sms1 = new ServerController();
        String path = "";
        JFileChooser j = new JFileChooser();
        j.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int x = j.showSaveDialog(this);

        if (x == JFileChooser.APPROVE_OPTION) {
            path = j.getSelectedFile().getPath();
        }
        
        sms1.viewreport(path);
        
        JOptionPane.showMessageDialog(rootPane, "Report Generated");
        
        
        String path1 = "";
        JFileChooser j1 = new JFileChooser();
        j1.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int x1 = j1.showSaveDialog(this);

        if (x1 == JFileChooser.APPROVE_OPTION) {
            path1 = j1.getSelectedFile().getPath();
        }
        
        sms1.viewreportatt(path1);
        
        JOptionPane.showMessageDialog(rootPane, "Report Generated");
        
        String path2 = "";
        JFileChooser j2 = new JFileChooser();
        j2.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int x2 = j2.showSaveDialog(this);

        if (x2 == JFileChooser.APPROVE_OPTION) {
            path2 = j2.getSelectedFile().getPath();
        }
        
        sms1.viewreportleave(path2);
        
        JOptionPane.showMessageDialog(rootPane, "Report Generated");
    }//GEN-LAST:event_btngeneratepdfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addattendancetable;
    private javax.swing.JPanel addleavetable;
    private javax.swing.JTextArea addnote;
    private javax.swing.JPanel addnotes;
    private javax.swing.JPanel addreportscard;
    private javax.swing.JPanel addusertable;
    private javax.swing.JButton btnaddattendancetable;
    private javax.swing.JButton btnaddleavetable1;
    private javax.swing.JButton btnaddnote;
    private javax.swing.JButton btnaddnotes;
    private javax.swing.JButton btnaddreports;
    private javax.swing.JButton btnaddusertable;
    private javax.swing.JButton btnchangesettings;
    private javax.swing.JButton btnconfirm;
    private javax.swing.JButton btngeneratepdf;
    private javax.swing.JButton btnmainmenu;
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton btnviewreports;
    private javax.swing.JPanel changesettingscard;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton mainmenuar;
    private javax.swing.JPanel mainmenucard;
    private javax.swing.JButton mainmenuvr;
    private javax.swing.JPasswordField settingscpw;
    private javax.swing.JTextField settingsnpw;
    private javax.swing.JTextField settingsnun;
    private javax.swing.JPasswordField settingspw;
    private javax.swing.JTextField settingsun;
    private javax.swing.JTable tableatt;
    private javax.swing.JTable tableleave;
    private javax.swing.JTable tableuser;
    private javax.swing.JTable tablevr;
    private javax.swing.JComboBox<String> viewreportmonth;
    private javax.swing.JPanel viewreportscard;
    private javax.swing.JComboBox<String> viewreportyear;
    // End of variables declaration//GEN-END:variables

   
    
}
